name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Adjust branch as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest
          
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
         host: ${{ secrets.EC2_HOST }}
         username: ec2-user # or ubuntu
         key: ${{ secrets.EC2_SSH_KEY }}
         script: |
           docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
           docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest
           docker stop my-app || true && docker rm my-app || true
           docker run -d --name my-app -p 80:3000 ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest
           
